#!/bin/sh

. /etc/openwrt_release

CPUINFO_PATH="/proc/cpuinfo"
CPUFREQ_PATH="/sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq"

cpu_arch="$(awk -F ': ' '/model name/ {print $2}' "$CPUINFO_PATH" 2>/dev/null | head -n1)"
if [ -z "$cpu_arch" ]; then
	cpu_part="$(awk -F ': ' '/CPU part/ {print $2}' "$CPUINFO_PATH" 2>/dev/null | head -n1)"
	case "$cpu_part" in
		0xd03) cpu_arch="ARM Cortex-A53" ;;
		0xd05) cpu_arch="ARM Cortex-A55" ;;
		0xd07) cpu_arch="ARM Cortex-A57" ;;
		0xd08) cpu_arch="ARM Cortex-A72" ;;
		0xd09) cpu_arch="ARM Cortex-A73" ;;
		0xd0a) cpu_arch="ARM Cortex-A75" ;;
		0xd0b) cpu_arch="ARM Cortex-A76" ;;
		0xd40) cpu_arch="ARM Neoverse V1" ;;
		*)
			cpu_arch="$(awk -F ': ' '/Processor/ {print $2}' "$CPUINFO_PATH" 2>/dev/null | head -n1)"
			[ -z "$cpu_arch" ] && cpu_arch="$(uname -m)"
			;;
	esac
fi

case "$DISTRIB_TARGET" in
x86/*)
	cpu_cores="$(cat "$CPUINFO_PATH" 2>/dev/null | awk -F ': ' '/cpu cores/ {print $2}' | head -n1)C $(grep -c "processor" "$CPUINFO_PATH")T"
	;;
*)
	cpu_cores="$(grep -c "processor" "$CPUINFO_PATH")"
	;;
esac

case "$DISTRIB_TARGET" in
bcm27xx/*)
	cpu_freq="$(( $(vcgencmd measure_clock arm | awk -F '=' '{print $2}') / 1000000 ))MHz"
	;;
bcm53xx/*)
	cpu_freq="$(nvram get clkfreq | awk -F ',' '{print $1}')MHz"
	;;
x86/*)
	cpu_freq="$(cat "$CPUINFO_PATH" 2>/dev/null | awk -F ': ' '/cpu MHz/ {print $2}' | head -n1)MHz"
	;;
*)
	cpu_freq="$(cat "$CPUFREQ_PATH" 2>/dev/null | awk '{printf("%.1fMHz", $0 / 1000)}')"
	;;
esac

if [ -n "$cpu_freq" ]; then
	echo -n "$cpu_arch x $cpu_cores ($cpu_freq)"
else
	echo -n "$cpu_arch x $cpu_cores"
fi
